package Talk;


/**
* Talk/genericError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* mercredi 26 octobre 2016 14 h 34 CEST
*/

public final class genericError extends org.omg.CORBA.UserException
{
  public String reason = null;

  public genericError ()
  {
    super(genericErrorHelper.id());
  } // ctor

  public genericError (String _reason)
  {
    super(genericErrorHelper.id());
    reason = _reason;
  } // ctor


  public genericError (String $reason, String _reason)
  {
    super(genericErrorHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class genericError
