package Talk;


/**
* Talk/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* mercredi 26 octobre 2016 14 h 34 CEST
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String msg = null;
  public String author = null;
  public String dst = null;

  public Message ()
  {
  } // ctor

  public Message (String _msg, String _author, String _dst)
  {
    msg = _msg;
    author = _author;
    dst = _dst;
  } // ctor

} // class Message
