package Talk;


/**
* Talk/Step1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* mercredi 26 octobre 2016 14 h 34 CEST
*/

public interface Step1Operations 
{
  void printMsg (Talk.Message m);
} // interface Step1Operations
