package Talk;


/**
* Talk/Step1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* vendredi 4 novembre 2016 15 h 14 CET
*/

public interface Step1 extends Step1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Step1
