package Talk;


/**
* Talk/Step1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* vendredi 4 novembre 2016 15 h 14 CET
*/

public interface Step1Operations 
{
  void printMsg (Talk.Message m);
} // interface Step1Operations
