package Talk;


/**
* Talk/Step2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* vendredi 28 octobre 2016 19 h 50 CEST
*/

public interface Step2 extends Step2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Step2
