package Talk;


/**
* Talk/Step2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* vendredi 28 octobre 2016 19 h 50 CEST
*/

public interface Step2Operations 
{
  void printMsg (Talk.Message m);
} // interface Step2Operations
