package Talk;


/**
* Talk/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* vendredi 4 novembre 2016 15 h 14 CET
*/

public interface ChatOperations 
{
  void inscription (Talk.Step1 s) throws Talk.genericError;
  void diffusion (Talk.Message m);
} // interface ChatOperations
