package Talk;


/**
* Talk/Step2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* jeudi 3 novembre 2016 17 h 12 CET
*/

public interface Step2 extends Step2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Step2
