package Talk;


/**
* Talk/Step2Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* jeudi 3 novembre 2016 17 h 12 CET
*/

abstract public class Step2Helper
{
  private static String  _id = "IDL:Talk/Step2:1.0";

  public static void insert (org.omg.CORBA.Any a, Talk.Step2 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Talk.Step2 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Talk.Step2Helper.id (), "Step2");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Talk.Step2 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Step2Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Talk.Step2 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Talk.Step2 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Talk.Step2)
      return (Talk.Step2)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Talk._Step2Stub stub = new Talk._Step2Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Talk.Step2 unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Talk.Step2)
      return (Talk.Step2)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Talk._Step2Stub stub = new Talk._Step2Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
