package Talk;


/**
* Talk/Step2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* jeudi 3 novembre 2016 17 h 12 CET
*/

public interface Step2Operations 
{
  void printMsg (Talk.Message m);
} // interface Step2Operations
