package Talk;


/**
* Talk/vecteurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* jeudi 3 novembre 2016 16 h 17 CET
*/

public final class vecteurHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public vecteurHolder ()
  {
  }

  public vecteurHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Talk.vecteurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Talk.vecteurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Talk.vecteurHelper.type ();
  }

}
