/***************************
* Contrat IDL de CorbaTalk *
***************************/

module Talk {


	struct Message {
		string msg;
		string author;
		string dst; /* Personne ou salon (pour le chat) */
	};
	
	exception genericError {string reason;};

	interface Step1 {
		oneway void printMsg(in Message m);
	};
	
	/*
	interface Chat {
		void inscription(in Message m) raises (genericError);
		oneway void diffusion(in Message m) raises (genericError);
	};
	*/

};